name: Build Windows Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # allow the workflow to push back to the repo
          persist-credentials: true

      - name: Setup MSBuild tools
        uses: microsoft/setup-msbuild@v1

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64

      - name: Build (Release)
        run: |
          cd build
          cmake --build . --config Release

      - name: Package release
        run: |
          powershell -ExecutionPolicy ByPass -File ..\scripts\package_release.ps1 -BuildDir "PvP_BlockChain\\build\\Release" -OutDir "artifacts" -Version "${{ github.ref_name || 'dev' }}"

      - name: Copy packaged ZIP into web/releases and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Preparing web/releases folder"
          md web\releases 2>$null || true
          $zip = Get-ChildItem -Path artifacts -Filter '*.zip' | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if ($null -eq $zip) {
            echo "No zip artifact found in artifacts/"
            exit 0
          }
          echo "Copying $($zip.Name) to web/releases/GladiatorArena-latest.zip"
          Copy-Item $zip.FullName web\releases\GladiatorArena-latest.zip -Force
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add web/releases/GladiatorArena-latest.zip
          if (git commit -m "chore(release): update web/releases with latest build $($zip.Name)" ) {
            git push origin HEAD:${{ github.ref }}
          } else {
            echo "No changes to commit (file identical)"
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gladiator-release
          path: artifacts
*** End Patch